# Generated by Django 4.0.3 on 2022-04-04 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='icon1.png', upload_to=''),
        ),
    ]
