# Generated by Django 4.0.3 on 2022-04-30 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bundle_id',
            field=models.IntegerField(verbose_name='bundle_id'),
        ),
        migrations.AlterField(
            model_name='service',
            name='bundle_id',
            field=models.IntegerField(verbose_name='bundle_id'),
        ),
    ]
