# Generated by Django 4.0.4 on 2022-04-20 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bundle_id', models.IntegerField(max_length=6, verbose_name='bundle_id')),
                ('vendor_id', models.IntegerField(max_length=6, verbose_name='vendor_id')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='price')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField(max_length=6, verbose_name='customer_id')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('background', models.CharField(max_length=300, verbose_name='background')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(max_length=6, verbose_name='product_id')),
                ('product_type', models.CharField(max_length=255, verbose_name='product_type')),
                ('vendor_id', models.IntegerField(max_length=6, verbose_name='vendor_id')),
                ('bundle_id', models.IntegerField(max_length=6, verbose_name='bundle_id')),
                ('product_name', models.CharField(max_length=255, verbose_name='product_name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='price')),
                ('binding_contract', models.CharField(max_length=255, verbose_name='binding_contract')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.IntegerField(max_length=6, verbose_name='service_id')),
                ('service_type', models.CharField(max_length=255, verbose_name='service_type')),
                ('vendor_id', models.IntegerField(max_length=6, verbose_name='vendor_id')),
                ('bundle_id', models.IntegerField(max_length=6, verbose_name='bundle_id')),
                ('service_name', models.CharField(max_length=255, verbose_name='service_name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='price')),
                ('binding_contract', models.CharField(max_length=255, verbose_name='binding_contract')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_id', models.IntegerField(max_length=6, verbose_name='vendor_id')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wishlist_id', models.IntegerField(max_length=6, verbose_name='wishlist_id')),
                ('customer_id', models.IntegerField(max_length=6, verbose_name='customer_id')),
                ('service_id', models.IntegerField(max_length=6, verbose_name='service_id')),
                ('product_id', models.IntegerField(max_length=6, verbose_name='product_id')),
            ],
        ),
    ]
