# Generated by Django 4.0.4 on 2022-04-20 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_bundle_bundle_id_alter_bundle_vendor_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bundle',
            name='bundle_id',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_id',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='vendor_id',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='wishlist_id',
        ),
    ]
